[project]
name = "{{name}}"
version = "0.1.0"
description = "{{description}}"
license = "{{license}}"
authors = []
website = "{{website}}"
keywords = []

repository = "{{repo}}"
default_branch = "{{default_branch}}|default:'main'}}"
{%- if default_subdir -%}
default_subdir = "{{default_subdir}}"
{% endif %}
{%- if default_name -%}
default_name = "{{default_name}}"
{%- endif -%}
{%- if lang -%}
default_lang = "{{lang}}"
{%- elif default_lang -%}
default_lang = "{{default_lang}}"
{%- endif -%}

[variables]
