[project]
name = "{{name}}"
version = "0.1.0"
description = "{{description}}"
license = "{{license}}"
authors = []
website = "{{website}}"
keywords = []

repository = "{{repo}}"
default_name = "{{name}}"
default_lang = "{{lang}}"
default_branch = "main"
default_subdir = "{{default_subdir}}"

[variables]
lang = "{{lang}}"
extension = "{{extension}}"
